/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import Process.ChucNang;
import Process.DatabaseManager;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class QUANLYSANPHAM extends javax.swing.JFrame {

    /**
     * Creates new form QUANLYSANPHAM
     */
    private Admin admin;

    public QUANLYSANPHAM() {
        initComponents();
        JButton btnBackToAdmin = new JButton("BACK");
        btnBackToAdmin.setBounds(10, 20, 70, 30);

        // Thêm sự kiện ActionListener cho nút
        btnBackToAdmin.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                if (admin != null) {
                    admin.setVisible(true);
                    setVisible(false);
                }
            }
        });

        // Thêm nút vào form
        this.add(btnBackToAdmin);
        this.setLocationRelativeTo(null);
        dfTableModel = (DefaultTableModel) tbl.getModel();
        ReloadTableProduct();
        ReloadComboBoxLoaiSP();
    }

    void ReloadSanPhamTheoLoaiDaChon() {
        String tenloai = (String) cbLoaiSP.getSelectedItem();
        System.out.println("tên loại: " + tenloai);
        dfTableModel.setRowCount(0);
        if (DatabaseManager.SanPhamToTable_ByLoaiSP(tbl, tenloai) == false) {
            JOptionPane.showMessageDialog(null, "Không có sản phẩm nào thuộc loại này", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    void ReloadComboBoxLoaiSP() {
        if (!DatabaseManager.LoaiSanPhamToCombox(cbLoaiSP)) {
            JOptionPane.showMessageDialog(null, "Tải dữ liệu lỗi, vui lòng thử lại sau", "Lỗi CSDL", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMaSanPham = new javax.swing.JTextField();
        txtGiaBan = new javax.swing.JTextField();
        txtTenSanPham = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnNotSave = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        cbLoaiSP = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 255));
        jLabel1.setText("QUẢN LÝ SẢN PHẨM");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Mã sản phẩm: ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Giá bán:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Tên sản phẩm:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Loại sp:");

        btnAdd.setText("Thêm");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa ");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnDelete.setText("Xoá");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnSave.setText("Lưu");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnNotSave.setText("K.Lưu");

        btnExit.setText("Thoát");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Giá bán", "Loại sp"
            }
        ));
        jScrollPane1.setViewportView(tbl);

        cbLoaiSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLoaiSPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(259, 259, 259))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAdd)
                        .addGap(18, 18, 18)
                        .addComponent(btnSua)
                        .addGap(28, 28, 28)
                        .addComponent(btnDelete)
                        .addGap(29, 29, 29)
                        .addComponent(btnSave)
                        .addGap(31, 31, 31)
                        .addComponent(btnNotSave)
                        .addGap(18, 18, 18)
                        .addComponent(btnExit)
                        .addGap(93, 93, 93))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMaSanPham)
                                    .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTenSanPham)
                                    .addComponent(cbLoaiSP, 0, 224, Short.MAX_VALUE))))
                        .addGap(45, 45, 45))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(txtMaSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbLoaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnSua)
                    .addComponent(btnDelete)
                    .addComponent(btnSave)
                    .addComponent(btnNotSave)
                    .addComponent(btnExit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    DefaultTableModel dfTableModel;
    int chucNangDaChon = ChucNang.NONE;

    private void SwitchMode(int chucNang) {
        chucNangDaChon = chucNang;
        switch (chucNang) {
            // khi nhấn vào nút thêm
            case ChucNang.ADD: {
                boolean trangThai = true;
                txtMaSanPham.setEnabled(trangThai);
                txtTenSanPham.setEnabled(trangThai);
                txtGiaBan.setEnabled(trangThai);
                cbLoaiSP.setEnabled(trangThai);

                txtMaSanPham.requestFocus(); // làm nổi bật lên khi có sự tương tác từ chuột hoặc bàn phím
                btnSave.setEnabled(trangThai); // nút Lưu hiện lên
                btnSua.setEnabled(!trangThai); // nút sửa xám đi
                btnDelete.setEnabled(!trangThai); // nút xoá xám đi
                btnNotSave.setEnabled(trangThai); // nút K.Lưu hiện lên

                txtMaSanPham.setText("");
                txtTenSanPham.setText("");
                txtGiaBan.setText("");
                cbLoaiSP.setSelectedItem("");
                btnAdd.setText("Hủy"); // nút thêm sẽ thành nút huỷ
                break;
            }

            // khi nhấn vào nút lưu
            case ChucNang.UPDATE: {
                boolean trangThai = true;
                txtTenSanPham.setEnabled(trangThai);
                txtGiaBan.setEnabled(trangThai);
                cbLoaiSP.setEnabled(trangThai);

                txtTenSanPham.requestFocus();

                btnSave.setEnabled(trangThai);
                btnAdd.setEnabled(!trangThai);
                btnDelete.setEnabled(!trangThai);
                btnNotSave.setEnabled(trangThai); // nút K.Lưu hiện lên

                btnSua.setText("Hủy");
                break;
            }

            // khi nhấn vào nút huỷ
            case ChucNang.NONE: {
                boolean trangThai = false;
                txtMaSanPham.setEnabled(trangThai);
                txtTenSanPham.setEnabled(trangThai);
                txtGiaBan.setEnabled(trangThai);
                cbLoaiSP.setEnabled(trangThai);
                btnSave.setEnabled(trangThai);
                btnAdd.setEnabled(true);
                btnSua.setEnabled(true);
                btnDelete.setEnabled(true);
                btnAdd.setText("Thêm");
                btnSua.setText("Sửa");
            }
        }
    }

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if (chucNangDaChon == ChucNang.NONE)
            SwitchMode(ChucNang.ADD);
        else
            SwitchMode(ChucNang.NONE);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        if (tbl.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Chưa chọn sản phẩm để sửa", "Chưa chọn sản phẩm", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (chucNangDaChon == ChucNang.NONE)
            SwitchMode(ChucNang.UPDATE);
        else
            SwitchMode(ChucNang.NONE);
    }//GEN-LAST:event_btnSuaActionPerformed
    private void ReloadTableProduct() {
        if (DatabaseManager.ProductToTable(tbl) == false) {
            JOptionPane.showMessageDialog(null, "Lấy dữ liệu sản phẩm có lỗi", "Có lỗi xảy ra", JOptionPane.ERROR_MESSAGE);
        }
    }
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = tbl.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn sản phẩm nào để xóa", "Chưa chọn lớp", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        int result = JOptionPane.showConfirmDialog(null, "Bạn có muốn xóa sản phẩm này không", "Xóa lớp?",
                JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (result == JOptionPane.CANCEL_OPTION) {
            return;
        }
        String masp = (String) tbl.getValueAt(selectedRow, 0);
        if (DatabaseManager.DeleteProduct(masp)) {
            btnAdd.requestFocus();
            SwitchMode(ChucNang.NONE);
            ReloadTableProduct();
            JOptionPane.showMessageDialog(null, "Xóa thành công", "Thành công", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Xóa thất bại", "Có lỗi xảy ra", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed
    void tbl_SelectionChanged() {
        int row = tbl.getSelectedRow();
        if (row >= 0) {

            String masp = (String) dfTableModel.getValueAt(row, 0);
            String tensp = (String) dfTableModel.getValueAt(row, 1);
            Double gia = (Double) dfTableModel.getValueAt(row, 2);

            txtMaSanPham.setText(masp.trim());
            txtTenSanPham.setText(tensp.trim());
            txtGiaBan.setText(gia.toString().trim());
//            cbLoaiSP.setSelectedItem(loaisp.trim());

        } else {
            txtMaSanPham.setText("");
            txtTenSanPham.setText("");
            txtGiaBan.setText("");
//            cbLoaiSP.setSelectedItem("");

        }
    }

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        tbl.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                tbl_SelectionChanged();
            }

        });
        ReloadTableProduct();

    }//GEN-LAST:event_formWindowOpened
    private boolean CheckInput() {
        String masp = txtMaSanPham.getText().trim();
        String tensp = txtTenSanPham.getText().trim();
        String gia = txtGiaBan.getText().trim();
        String loaisp = cbLoaiSP.getSelectedItem().toString().trim();

        if (masp.length() == 0) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập mã số lớp", "Chưa  nhập mã số lớp", JOptionPane.WARNING_MESSAGE);
            txtMaSanPham.requestFocus();
            return false;
        }
        if (tensp.length() == 0) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập tên lớp", "Chưa nhập tên lớp", JOptionPane.WARNING_MESSAGE);
            txtTenSanPham.requestFocus();
            return false;
        }
        if (gia.length() == 0) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập giáo viên chủ nhiệm", "Chưa nhập giáo viên chủ nhiệm", JOptionPane.WARNING_MESSAGE);
            txtGiaBan.requestFocus();
            return false;
        }
        if (loaisp.length() == 0) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập giáo viên chủ nhiệm", "Chưa nhập giáo viên chủ nhiệm", JOptionPane.WARNING_MESSAGE);
            cbLoaiSP.requestFocus();
            return false;
        }
        return true;
    }
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String masp = txtMaSanPham.getText().trim(); // loại bỏ khoảng trắng không cần thiết từ đầu và cuối
        String tensp = txtTenSanPham.getText().trim();
        String gia = txtGiaBan.getText().trim();
        String loaisp = cbLoaiSP.getSelectedItem().toString().trim(); // 'Mũ'
        if (chucNangDaChon == ChucNang.ADD) {
            if (CheckInput() == false) {
                return;
            }
            if (DatabaseManager.Count("SANPHAM", "MASP", masp) > 0) {
                txtMaSanPham.requestFocus();
                JOptionPane.showMessageDialog(null, "Mã sản phẩm bạn nhập đã tồn tại trong csdl", "Trùng mã", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (DatabaseManager.AddProduct(masp, tensp, gia, loaisp)) {
                btnAdd.requestFocus();
                SwitchMode(ChucNang.NONE);
                ReloadTableProduct();
                JOptionPane.showMessageDialog(null, "Thêm thành công", "Thành công", JOptionPane.INFORMATION_MESSAGE);
                return;
            } else {
                JOptionPane.showMessageDialog(null, "Thêm thất bại", "Có lỗi xảy ra", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        if (chucNangDaChon == ChucNang.UPDATE) {
            if (CheckInput() == false) {
                return;
            }
            if (DatabaseManager.EditProduct(masp, tensp, gia, loaisp)) {

                btnSua.requestFocus();
                SwitchMode(ChucNang.NONE);
                ReloadTableProduct();
                JOptionPane.showMessageDialog(null, "Sửa thành công", "Thành công", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Sửa thất bại", "Có lỗi ", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed
    private void Exit() {
        int result = JOptionPane.showConfirmDialog(null, "Bạn có muốn thoát không?", "Thoát?", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (result == JOptionPane.CANCEL_OPTION) {
            return;
        }
        this.dispose();
    }
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Exit();
    }//GEN-LAST:event_formWindowClosing

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        Exit();
    }//GEN-LAST:event_btnExitActionPerformed

    private void cbLoaiSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLoaiSPActionPerformed
        ReloadSanPhamTheoLoaiDaChon();
    }//GEN-LAST:event_cbLoaiSPActionPerformed

    public void setAdmin(Admin admin) {
        this.admin = admin;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QUANLYSANPHAM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QUANLYSANPHAM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QUANLYSANPHAM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QUANLYSANPHAM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QUANLYSANPHAM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnNotSave;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSua;
    private javax.swing.JComboBox<String> cbLoaiSP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txtGiaBan;
    private javax.swing.JTextField txtMaSanPham;
    private javax.swing.JTextField txtTenSanPham;
    // End of variables declaration//GEN-END:variables

}
