/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import Process.DatabaseManager;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Admin
 */
public class XEMSANPHAMTHEOLOAI extends javax.swing.JFrame {

    /**
     * Creates new form XEMSANPHAMTHEOLOAI
     */
    private Admin admin;

    public XEMSANPHAMTHEOLOAI() {
        initComponents();
        // Khởi tạo nút "Quay lại Admin"
        JButton btnBackToAdmin = new JButton("BACK");
        btnBackToAdmin.setBounds(10, 30, 70, 30);

        // Thêm sự kiện ActionListener cho nút
        btnBackToAdmin.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                if (admin != null) {
                    admin.setVisible(true);
                    setVisible(false);
                }
            }
        });
        LoadComboBoxData();
        // Thêm nút vào form
        this.add(btnBackToAdmin);
        this.setLocationRelativeTo(null);
    }

    private void LoadComboBoxData() {
        ArrayList<String> productTypes = DatabaseManager.LayDataLoaiSP();
        if (!productTypes.isEmpty()) {
            // Nếu lấy dữ liệu thành công, thực hiện thêm dữ liệu vào ComboBox
            for (String type : productTypes) {
                cbChooseProduct.addItem(type);
            }
        } else {
            // Xử lý trường hợp không có dữ liệu
            JOptionPane.showMessageDialog(null, "Không thể tải dữ liệu loại sản phẩm", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }

    void ReloadSanPhamTheoLoaiDaChon() {
        String tenloai = (String) cbChooseProduct.getSelectedItem();
        System.out.println("tên loại: " + tenloai);
        if (DatabaseManager.SanPhamToTable_ByLoaiSP(tbl, tenloai) == false) {
            JOptionPane.showMessageDialog(null, "Không có sản phẩm nào thuộc loại này", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    void ReloadComboBoxLoaiSP() {
        if (!DatabaseManager.LoaiSanPhamToCombox(cbChooseProduct)) {
            JOptionPane.showMessageDialog(null, "Tải dữ liệu lỗi, vui lòng thử lại sau", "Lỗi CSDL", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }

    void Exit() {
        int result = JOptionPane.showConfirmDialog(null, "Bạn muốn thoát không?",
                "Thoát?", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (result == JOptionPane.CANCEL_OPTION) {
            return;
        }
        this.dispose();
        if (admin != null) {
            admin.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbChooseProduct = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 420));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 255));
        jLabel1.setText("XEM SẢN PHẨM THEO LOẠI");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Chọn loại sản phẩm: ");

        cbChooseProduct.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbChooseProductItemStateChanged(evt);
            }
        });

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MÃ SẢN PHẨM", "TÊN SẢN PHẨM", "ĐƠN GIÁ", "MÃ LOẠI"
            }
        ));
        jScrollPane1.setViewportView(tbl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel2)
                        .addGap(11, 11, 11)
                        .addComponent(cbChooseProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(cbChooseProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void tbl_SelectionChanged() {

    }
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Exit();
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ReloadComboBoxLoaiSP();
    }//GEN-LAST:event_formWindowOpened

    private void cbChooseProductItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbChooseProductItemStateChanged
        ReloadSanPhamTheoLoaiDaChon();
    }//GEN-LAST:event_cbChooseProductItemStateChanged
    public void setAdmin(Admin admin) {
        this.admin = admin;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(XEMSANPHAMTHEOLOAI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(XEMSANPHAMTHEOLOAI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(XEMSANPHAMTHEOLOAI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(XEMSANPHAMTHEOLOAI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new XEMSANPHAMTHEOLOAI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbChooseProduct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl;
    // End of variables declaration//GEN-END:variables

}
